package ohi.andre.consolelauncher.managers.xml.options

import ohi.andre.consolelauncher.R
import ohi.andre.consolelauncher.managers.xml.XMLPrefsManager
import ohi.andre.consolelauncher.managers.xml.classes.XMLPrefsElement
import ohi.andre.consolelauncher.managers.xml.classes.XMLPrefsSave

private val TRANSPARENT_INVALID: Array<String?> = arrayOf("#ff000000")

enum class Theme(
    private val defaultValue: String,
    private val info: Int,
    private val invalidValues: Array<String?>? = null,
    private val kind: String = XMLPrefsSave.COLOR,
    val advanced: Boolean = false
) : XMLPrefsSave {
    background_color("#00000000", R.string.setting_theme_background_color_description),
    wallpaper_overlay_color("#00000000", R.string.setting_theme_wallpaper_overlay_color_description),
    settings_wallpaper_overlay_color("#66000000", R.string.setting_theme_settings_wallpaper_overlay_color_description),

    input_text_color("#ff00ff00", R.string.setting_theme_input_text_color_description),
    output_text_color("#ffffffff", R.string.setting_theme_output_text_color_description),
    cursor_color("#ffffff", R.string.setting_theme_cursor_color_description),
    enter_icon_color("#ffffffff", R.string.setting_theme_enter_icon_color_description),
    toolbar_icon_color("#ffffff", R.string.setting_theme_toolbar_icon_color_description),
    toolbar_background_color("#00000000", R.string.setting_theme_toolbar_background_color_description),
    restart_message_text_color("#ffffffff", R.string.setting_theme_restart_message_text_color_description),
    session_info_text_color("#888888", R.string.setting_theme_session_info_text_color_description),

    device_text_color("#ffff9800", R.string.setting_theme_device_text_color_description),
    battery_text_high("#4CAF50", R.string.setting_theme_battery_text_high_description),
    battery_text_medium("#FFEB3B", R.string.setting_theme_battery_text_medium_description),
    battery_text_low("#FF5722", R.string.setting_theme_battery_text_low_description),
    ascii_text_color("#00FF00", R.string.setting_theme_ascii_text_color_description),
    time_text_color("#03A9F4", R.string.setting_theme_time_text_color_description),
    storage_text_color("#9C27B0", R.string.setting_theme_storage_text_color_description),
    ram_text_color("#fff44336", R.string.setting_theme_ram_text_color_description),
    network_info_text_color("#FFCA28", R.string.setting_theme_network_info_text_color_description),
    weather_text_color("#fff44336", R.string.setting_theme_weather_text_color_description),
    unlock_counter_text_color("#ffff9800", R.string.setting_theme_unlock_counter_text_color_description),

    ram_status_background_color("#00000000", R.string.setting_theme_ram_status_background_color_description, TRANSPARENT_INVALID),
    device_status_background_color("#00000000", R.string.setting_theme_device_status_background_color_description, TRANSPARENT_INVALID),
    time_status_background_color("#00000000", R.string.setting_theme_time_status_background_color_description, TRANSPARENT_INVALID),
    battery_status_background_color("#00000000", R.string.setting_theme_battery_status_background_color_description, TRANSPARENT_INVALID),
    storage_status_background_color("#00000000", R.string.setting_theme_storage_status_background_color_description, TRANSPARENT_INVALID),
    network_status_background_color("#00000000", R.string.setting_theme_network_status_background_color_description, TRANSPARENT_INVALID),
    notes_status_background_color("#00000000", R.string.setting_theme_notes_status_background_color_description, TRANSPARENT_INVALID),
    weather_status_background_color("#00000000", R.string.setting_theme_weather_status_background_color_description, TRANSPARENT_INVALID),
    unlock_status_background_color("#00000000", R.string.setting_theme_unlock_status_background_color_description, TRANSPARENT_INVALID),
    ascii_status_background_color("#00000000", R.string.setting_theme_ascii_status_background_color_description, TRANSPARENT_INVALID),
    unified_status_background_color("#00000000", R.string.setting_theme_unified_status_background_color_description, TRANSPARENT_INVALID),

    ram_status_text_shadow_color("#00000000", R.string.setting_theme_ram_status_text_shadow_color_description, TRANSPARENT_INVALID),
    device_status_text_shadow_color("#00000000", R.string.setting_theme_device_status_text_shadow_color_description, TRANSPARENT_INVALID),
    time_status_text_shadow_color("#00000000", R.string.setting_theme_time_status_text_shadow_color_description, TRANSPARENT_INVALID),
    battery_status_text_shadow_color("#00000000", R.string.setting_theme_battery_status_text_shadow_color_description, TRANSPARENT_INVALID),
    storage_status_text_shadow_color("#00000000", R.string.setting_theme_storage_status_text_shadow_color_description, TRANSPARENT_INVALID),
    network_status_text_shadow_color("#00000000", R.string.setting_theme_network_status_text_shadow_color_description, TRANSPARENT_INVALID),
    notes_status_text_shadow_color("#00000000", R.string.setting_theme_notes_status_text_shadow_color_description, TRANSPARENT_INVALID),
    weather_status_text_shadow_color("#00000000", R.string.setting_theme_weather_status_text_shadow_color_description, TRANSPARENT_INVALID),
    unlock_status_text_shadow_color("#00000000", R.string.setting_theme_unlock_status_text_shadow_color_description, TRANSPARENT_INVALID),
    ascii_status_text_shadow_color("#00000000", R.string.setting_theme_ascii_status_text_shadow_color_description, TRANSPARENT_INVALID),

    alias_content_text_color("#1DE9B6", R.string.setting_theme_alias_content_text_color_description),
    app_installed_text_color("#FF7043", R.string.setting_theme_app_installed_text_color_description),
    app_uninstalled_text_color("#FF7043", R.string.setting_theme_app_uninstalled_text_color_description),
    regex_match_background_color("#CDDC39", R.string.setting_theme_regex_match_background_color_description),
    notes_text_color("#8BC34A", R.string.setting_theme_notes_text_color_description),
    locked_notes_text_color("#3D5AFE", R.string.setting_theme_locked_notes_text_color_description),
    link_text_color("#0000EE", R.string.setting_theme_link_text_color_description),
    apps_drawer_text_color("#A5D6A7", R.string.setting_theme_apps_drawer_text_color_description),

    input_background_color("#00000000", R.string.setting_theme_input_background_color_description, TRANSPARENT_INVALID),
    output_background_color("#00000000", R.string.setting_theme_output_background_color_description, TRANSPARENT_INVALID),
    suggestions_background_color("#00000000", R.string.setting_theme_suggestions_background_color_description, TRANSPARENT_INVALID),
    input_text_shadow_color("#00000000", R.string.setting_theme_input_text_shadow_color_description, TRANSPARENT_INVALID),
    output_text_shadow_color("#00000000", R.string.setting_theme_output_text_shadow_color_description, TRANSPARENT_INVALID),
    terminal_border_color("#ffffffff", R.string.setting_theme_terminal_border_color_description),
    module_button_background_color("#00000000", R.string.setting_theme_module_button_background_color_description),
    module_text_color("#ffffffff", R.string.setting_theme_module_text_color_description),
    terminal_window_background_color("#00000000", R.string.setting_theme_terminal_window_background_color_description),
    terminal_header_background_color("#00000000", R.string.setting_theme_terminal_header_background_color_description),
    terminal_header_border_color("#ffffffff", R.string.setting_theme_terminal_header_border_color_description),

    // Advanced semantic roles inherit from the compact core palette until overridden.
    accent_color("auto"),
    muted_text_color("auto"),
    success_text_color("auto"),
    warning_text_color("auto"),
    error_text_color("auto"),
    divider_color("auto"),
    focus_color("auto"),
    disabled_text_color("auto"),
    disabled_background_color("auto"),
    selection_background_color("auto"),
    selection_text_color("auto"),
    selection_border_color("auto"),
    pressed_background_color("auto"),
    pressed_text_color("auto"),
    pressed_border_color("auto"),

    button_background_color("auto"),
    button_text_color("auto"),
    button_border_color("auto"),
    primary_button_background_color("auto"),
    primary_button_text_color("auto"),
    primary_button_border_color("auto"),
    icon_button_background_color("auto"),
    icon_button_color("auto"),
    icon_button_border_color("auto"),
    field_background_color("auto"),
    field_text_color("auto"),
    field_hint_color("auto"),
    field_border_color("auto"),
    list_row_background_color("auto"),
    list_row_text_color("auto"),
    list_row_border_color("auto"),
    list_selected_background_color("auto"),
    list_selected_text_color("auto"),
    list_selected_border_color("auto"),
    toggle_off_background_color("auto"),
    toggle_off_text_color("auto"),
    toggle_off_border_color("auto"),
    toggle_on_background_color("auto"),
    toggle_on_text_color("auto"),
    toggle_on_border_color("auto"),
    slider_track_color("auto"),
    slider_progress_color("auto"),
    slider_thumb_color("auto"),
    chip_background_color("auto"),
    chip_text_color("auto"),
    chip_border_color("auto"),
    tab_background_color("auto"),
    tab_text_color("auto"),
    tab_border_color("auto"),

    app_drawer_panel_background_color("auto"),
    app_drawer_panel_text_color("auto"),
    app_drawer_panel_border_color("auto"),
    app_drawer_header_background_color("auto"),
    app_drawer_header_text_color("auto"),
    app_drawer_header_border_color("auto"),
    app_drawer_row_background_color("auto"),
    app_drawer_row_text_color("auto"),
    app_drawer_group_background_color("auto"),
    app_drawer_group_text_color("auto"),
    app_drawer_group_border_color("auto"),
    app_drawer_selection_background_color("auto"),
    app_drawer_selection_text_color("auto"),
    app_drawer_selection_border_color("auto"),

    module_panel_background_color("auto"),
    module_panel_text_color("auto"),
    module_panel_border_color("auto"),
    module_header_background_color("auto"),
    module_header_text_color("auto"),
    module_header_border_color("auto"),
    module_dock_background_color("auto"),
    module_dock_text_color("auto"),
    module_dock_border_color("auto"),
    module_action_background_color("auto"),
    module_action_text_color("auto"),
    module_action_border_color("auto"),
    module_active_background_color("auto"),
    module_active_text_color("auto"),
    module_active_border_color("auto"),

    widget_panel_background_color("auto"),
    widget_panel_text_color("auto"),
    widget_panel_border_color("auto"),
    widget_header_background_color("auto"),
    widget_header_text_color("auto"),
    widget_header_border_color("auto"),
    widget_row_background_color("auto"),
    widget_row_text_color("auto"),
    widget_command_background_color("auto"),
    widget_command_text_color("auto"),
    widget_command_border_color("auto"),
    widget_control_background_color("auto"),
    widget_control_text_color("auto"),
    widget_control_border_color("auto"),

    workspace_panel_background_color("auto"),
    workspace_panel_text_color("auto"),
    workspace_panel_border_color("auto"),
    workspace_header_background_color("auto"),
    workspace_header_text_color("auto"),
    workspace_header_border_color("auto"),
    workspace_output_background_color("auto"),
    workspace_output_text_color("auto"),
    workspace_input_background_color("auto"),
    workspace_input_text_color("auto"),
    workspace_control_background_color("auto"),
    workspace_control_text_color("auto"),
    workspace_control_border_color("auto"),

    settings_screen_color("auto"),
    settings_panel_background_color("auto"),
    settings_panel_text_color("auto"),
    settings_panel_border_color("auto"),
    settings_header_background_color("auto"),
    settings_header_text_color("auto"),
    settings_header_border_color("auto"),
    settings_row_background_color("auto"),
    settings_row_text_color("auto"),
    settings_row_border_color("auto"),
    settings_input_background_color("auto"),
    settings_input_text_color("auto"),
    settings_input_hint_color("auto"),
    settings_input_border_color("auto"),

    dialog_scrim_color("auto"),
    dialog_panel_background_color("auto"),
    dialog_panel_text_color("auto"),
    dialog_panel_border_color("auto"),
    dialog_header_background_color("auto"),
    dialog_header_text_color("auto"),
    dialog_header_border_color("auto"),
    overlay_scrim_color("auto"),
    overlay_panel_background_color("auto"),
    overlay_panel_text_color("auto"),
    overlay_panel_border_color("auto"),
    overlay_header_background_color("auto"),
    overlay_header_text_color("auto"),
    overlay_header_border_color("auto"),

    ansi_black("auto"),
    ansi_red("auto"),
    ansi_green("auto"),
    ansi_yellow("auto"),
    ansi_blue("auto"),
    ansi_magenta("auto"),
    ansi_cyan("auto"),
    ansi_white("auto"),
    ansi_bright_black("auto"),
    ansi_bright_red("auto"),
    ansi_bright_green("auto"),
    ansi_bright_yellow("auto"),
    ansi_bright_blue("auto"),
    ansi_bright_magenta("auto"),
    ansi_bright_cyan("auto"),
    ansi_bright_white("auto");

    private constructor(defaultValue: String) : this(
        defaultValue,
        R.string.setting_theme_advanced_color_description,
        null,
        XMLPrefsSave.AUTO_COLOR,
        true
    )

    override fun parent(): XMLPrefsElement = XMLPrefsManager.XMLPrefsRoot.THEME

    override fun label(): String = name

    override fun type(): String = kind

    override fun defaultValue(): String = defaultValue

    override fun infoRes(): Int = info

    override fun invalidValues(): Array<String?>? = invalidValues

    override fun getLowercaseString(): String = label()

    override fun getString(): String = label()
}
