package ohi.andre.consolelauncher.managers.xml.options

import ohi.andre.consolelauncher.R
import ohi.andre.consolelauncher.managers.xml.XMLPrefsManager
import ohi.andre.consolelauncher.managers.xml.classes.XMLPrefsElement
import ohi.andre.consolelauncher.managers.xml.classes.XMLPrefsSave

private val TRANSPARENT_INVALID: Array<String?> = arrayOf("#ff000000")

enum class Theme(
    private val defaultValue: String,
    private val info: Int,
    private val invalidValues: Array<String?>? = null,
    private val kind: String = XMLPrefsSave.COLOR,
    val advanced: Boolean = false
) : XMLPrefsSave {
    background_color("#00000000", R.string.setting_theme_background_color_description),
    wallpaper_overlay_color("#00000000", R.string.setting_theme_wallpaper_overlay_color_description),
    settings_wallpaper_overlay_color("#66000000", R.string.setting_theme_settings_wallpaper_overlay_color_description),

    input_text_color("#ff00ff00", R.string.setting_theme_input_text_color_description),
    output_text_color("#ffffffff", R.string.setting_theme_output_text_color_description),
    cursor_color("#ffffff", R.string.setting_theme_cursor_color_description),
    enter_icon_color("#ffffffff", R.string.setting_theme_enter_icon_color_description),
    toolbar_icon_color("#ffffff", R.string.setting_theme_toolbar_icon_color_description),
    toolbar_background_color("#00000000", R.string.setting_theme_toolbar_background_color_description),
    restart_message_text_color("#ffffffff", R.string.setting_theme_restart_message_text_color_description),
    session_info_text_color("#888888", R.string.setting_theme_session_info_text_color_description),

    device_text_color("#ffff9800", R.string.setting_theme_device_text_color_description),
    battery_text_high("#4CAF50", R.string.setting_theme_battery_text_high_description),
    battery_text_medium("#FFEB3B", R.string.setting_theme_battery_text_medium_description),
    battery_text_low("#FF5722", R.string.setting_theme_battery_text_low_description),
    ascii_text_color("#00FF00", R.string.setting_theme_ascii_text_color_description),
    time_text_color("#03A9F4", R.string.setting_theme_time_text_color_description),
    storage_text_color("#9C27B0", R.string.setting_theme_storage_text_color_description),
    ram_text_color("#fff44336", R.string.setting_theme_ram_text_color_description),
    network_info_text_color("#FFCA28", R.string.setting_theme_network_info_text_color_description),
    weather_text_color("#fff44336", R.string.setting_theme_weather_text_color_description),
    unlock_counter_text_color("#ffff9800", R.string.setting_theme_unlock_counter_text_color_description),

    ram_status_background_color("#00000000", R.string.setting_theme_ram_status_background_color_description, TRANSPARENT_INVALID),
    device_status_background_color("#00000000", R.string.setting_theme_device_status_background_color_description, TRANSPARENT_INVALID),
    time_status_background_color("#00000000", R.string.setting_theme_time_status_background_color_description, TRANSPARENT_INVALID),
    battery_status_background_color("#00000000", R.string.setting_theme_battery_status_background_color_description, TRANSPARENT_INVALID),
    storage_status_background_color("#00000000", R.string.setting_theme_storage_status_background_color_description, TRANSPARENT_INVALID),
    network_status_background_color("#00000000", R.string.setting_theme_network_status_background_color_description, TRANSPARENT_INVALID),
    notes_status_background_color("#00000000", R.string.setting_theme_notes_status_background_color_description, TRANSPARENT_INVALID),
    weather_status_background_color("#00000000", R.string.setting_theme_weather_status_background_color_description, TRANSPARENT_INVALID),
    unlock_status_background_color("#00000000", R.string.setting_theme_unlock_status_background_color_description, TRANSPARENT_INVALID),
    ascii_status_background_color("#00000000", R.string.setting_theme_ascii_status_background_color_description, TRANSPARENT_INVALID),
    unified_status_background_color("#00000000", R.string.setting_theme_unified_status_background_color_description, TRANSPARENT_INVALID),

    ram_status_text_shadow_color("#00000000", R.string.setting_theme_ram_status_text_shadow_color_description, TRANSPARENT_INVALID),
    device_status_text_shadow_color("#00000000", R.string.setting_theme_device_status_text_shadow_color_description, TRANSPARENT_INVALID),
    time_status_text_shadow_color("#00000000", R.string.setting_theme_time_status_text_shadow_color_description, TRANSPARENT_INVALID),
    battery_status_text_shadow_color("#00000000", R.string.setting_theme_battery_status_text_shadow_color_description, TRANSPARENT_INVALID),
    storage_status_text_shadow_color("#00000000", R.string.setting_theme_storage_status_text_shadow_color_description, TRANSPARENT_INVALID),
    network_status_text_shadow_color("#00000000", R.string.setting_theme_network_status_text_shadow_color_description, TRANSPARENT_INVALID),
    notes_status_text_shadow_color("#00000000", R.string.setting_theme_notes_status_text_shadow_color_description, TRANSPARENT_INVALID),
    weather_status_text_shadow_color("#00000000", R.string.setting_theme_weather_status_text_shadow_color_description, TRANSPARENT_INVALID),
    unlock_status_text_shadow_color("#00000000", R.string.setting_theme_unlock_status_text_shadow_color_description, TRANSPARENT_INVALID),
    ascii_status_text_shadow_color("#00000000", R.string.setting_theme_ascii_status_text_shadow_color_description, TRANSPARENT_INVALID),

    alias_content_text_color("#1DE9B6", R.string.setting_theme_alias_content_text_color_description),
    app_installed_text_color("#FF7043", R.string.setting_theme_app_installed_text_color_description),
    app_uninstalled_text_color("#FF7043", R.string.setting_theme_app_uninstalled_text_color_description),
    regex_match_background_color("#CDDC39", R.string.setting_theme_regex_match_background_color_description),
    notes_text_color("#8BC34A", R.string.setting_theme_notes_text_color_description),
    locked_notes_text_color("#3D5AFE", R.string.setting_theme_locked_notes_text_color_description),
    link_text_color("#0000EE", R.string.setting_theme_link_text_color_description),
    apps_drawer_text_color("#A5D6A7", R.string.setting_theme_apps_drawer_text_color_description),

    input_background_color("#00000000", R.string.setting_theme_input_background_color_description, TRANSPARENT_INVALID),
    output_background_color("#00000000", R.string.setting_theme_output_background_color_description, TRANSPARENT_INVALID),
    suggestions_background_color("#00000000", R.string.setting_theme_suggestions_background_color_description, TRANSPARENT_INVALID),
    input_text_shadow_color("#00000000", R.string.setting_theme_input_text_shadow_color_description, TRANSPARENT_INVALID),
    output_text_shadow_color("#00000000", R.string.setting_theme_output_text_shadow_color_description, TRANSPARENT_INVALID),
    terminal_border_color("#ffffffff", R.string.setting_theme_terminal_border_color_description),
    module_button_background_color("#00000000", R.string.setting_theme_module_button_background_color_description),
    module_text_color("#ffffffff", R.string.setting_theme_module_text_color_description),
    terminal_window_background_color("#00000000", R.string.setting_theme_terminal_window_background_color_description),
    terminal_header_background_color("#00000000", R.string.setting_theme_terminal_header_background_color_description),
    terminal_header_border_color("#ffffffff", R.string.setting_theme_terminal_header_border_color_description),

    // Advanced colors inherit from the core palette or their parent role until overridden.
    accent_color(R.string.setting_theme_accent_color_description),
    muted_text_color(R.string.setting_theme_muted_text_color_description),
    success_text_color(R.string.setting_theme_success_text_color_description),
    warning_text_color(R.string.setting_theme_warning_text_color_description),
    error_text_color(R.string.setting_theme_error_text_color_description),
    divider_color(R.string.setting_theme_divider_color_description),
    focus_color(R.string.setting_theme_focus_color_description),
    disabled_text_color(R.string.setting_theme_disabled_text_color_description),
    disabled_background_color(R.string.setting_theme_disabled_background_color_description),
    selection_background_color(R.string.setting_theme_selection_background_color_description),
    selection_text_color(R.string.setting_theme_selection_text_color_description),
    selection_border_color(R.string.setting_theme_selection_border_color_description),
    pressed_background_color(R.string.setting_theme_pressed_background_color_description),
    pressed_text_color(R.string.setting_theme_pressed_text_color_description),
    pressed_border_color(R.string.setting_theme_pressed_border_color_description),

    button_background_color(R.string.setting_theme_button_background_color_description),
    button_text_color(R.string.setting_theme_button_text_color_description),
    button_border_color(R.string.setting_theme_button_border_color_description),
    primary_button_background_color(R.string.setting_theme_primary_button_background_color_description),
    primary_button_text_color(R.string.setting_theme_primary_button_text_color_description),
    primary_button_border_color(R.string.setting_theme_primary_button_border_color_description),
    icon_button_background_color(R.string.setting_theme_icon_button_background_color_description),
    icon_button_color(R.string.setting_theme_icon_button_color_description),
    icon_button_border_color(R.string.setting_theme_icon_button_border_color_description),
    field_background_color(R.string.setting_theme_field_background_color_description),
    field_text_color(R.string.setting_theme_field_text_color_description),
    field_hint_color(R.string.setting_theme_field_hint_color_description),
    field_border_color(R.string.setting_theme_field_border_color_description),
    list_row_background_color(R.string.setting_theme_list_row_background_color_description),
    list_row_text_color(R.string.setting_theme_list_row_text_color_description),
    list_row_border_color(R.string.setting_theme_list_row_border_color_description),
    list_selected_background_color(R.string.setting_theme_list_selected_background_color_description),
    list_selected_text_color(R.string.setting_theme_list_selected_text_color_description),
    list_selected_border_color(R.string.setting_theme_list_selected_border_color_description),
    toggle_off_background_color(R.string.setting_theme_toggle_off_background_color_description),
    toggle_off_text_color(R.string.setting_theme_toggle_off_text_color_description),
    toggle_off_border_color(R.string.setting_theme_toggle_off_border_color_description),
    toggle_on_background_color(R.string.setting_theme_toggle_on_background_color_description),
    toggle_on_text_color(R.string.setting_theme_toggle_on_text_color_description),
    toggle_on_border_color(R.string.setting_theme_toggle_on_border_color_description),
    slider_track_color(R.string.setting_theme_slider_track_color_description),
    slider_progress_color(R.string.setting_theme_slider_progress_color_description),
    slider_thumb_color(R.string.setting_theme_slider_thumb_color_description),
    chip_background_color(R.string.setting_theme_chip_background_color_description),
    chip_text_color(R.string.setting_theme_chip_text_color_description),
    chip_border_color(R.string.setting_theme_chip_border_color_description),
    tab_background_color(R.string.setting_theme_tab_background_color_description),
    tab_text_color(R.string.setting_theme_tab_text_color_description),
    tab_border_color(R.string.setting_theme_tab_border_color_description),

    app_drawer_panel_background_color(R.string.setting_theme_app_drawer_panel_background_color_description),
    app_drawer_panel_text_color(R.string.setting_theme_app_drawer_panel_text_color_description),
    app_drawer_panel_border_color(R.string.setting_theme_app_drawer_panel_border_color_description),
    app_drawer_header_background_color(R.string.setting_theme_app_drawer_header_background_color_description),
    app_drawer_header_text_color(R.string.setting_theme_app_drawer_header_text_color_description),
    app_drawer_header_border_color(R.string.setting_theme_app_drawer_header_border_color_description),
    app_drawer_row_background_color(R.string.setting_theme_app_drawer_row_background_color_description),
    app_drawer_row_text_color(R.string.setting_theme_app_drawer_row_text_color_description),
    app_drawer_group_background_color(R.string.setting_theme_app_drawer_group_background_color_description),
    app_drawer_group_text_color(R.string.setting_theme_app_drawer_group_text_color_description),
    app_drawer_group_border_color(R.string.setting_theme_app_drawer_group_border_color_description),
    app_drawer_selection_background_color(R.string.setting_theme_app_drawer_selection_background_color_description),
    app_drawer_selection_text_color(R.string.setting_theme_app_drawer_selection_text_color_description),
    app_drawer_selection_border_color(R.string.setting_theme_app_drawer_selection_border_color_description),

    module_panel_background_color(R.string.setting_theme_module_panel_background_color_description),
    module_panel_text_color(R.string.setting_theme_module_panel_text_color_description),
    module_panel_border_color(R.string.setting_theme_module_panel_border_color_description),
    module_header_background_color(R.string.setting_theme_module_header_background_color_description),
    module_header_text_color(R.string.setting_theme_module_header_text_color_description),
    module_header_border_color(R.string.setting_theme_module_header_border_color_description),
    module_header_control_background_color(R.string.setting_theme_module_header_control_background_color_description),
    module_dock_background_color(R.string.setting_theme_module_dock_background_color_description),
    module_dock_text_color(R.string.setting_theme_module_dock_text_color_description),
    module_dock_border_color(R.string.setting_theme_module_dock_border_color_description),
    module_action_background_color(R.string.setting_theme_module_action_background_color_description),
    module_action_text_color(R.string.setting_theme_module_action_text_color_description),
    module_action_border_color(R.string.setting_theme_module_action_border_color_description),
    module_active_background_color(R.string.setting_theme_module_active_background_color_description),
    module_active_text_color(R.string.setting_theme_module_active_text_color_description),
    module_active_border_color(R.string.setting_theme_module_active_border_color_description),

    widget_panel_background_color(R.string.setting_theme_widget_panel_background_color_description),
    widget_panel_text_color(R.string.setting_theme_widget_panel_text_color_description),
    widget_panel_border_color(R.string.setting_theme_widget_panel_border_color_description),
    widget_header_background_color(R.string.setting_theme_widget_header_background_color_description),
    widget_header_text_color(R.string.setting_theme_widget_header_text_color_description),
    widget_header_border_color(R.string.setting_theme_widget_header_border_color_description),
    widget_row_background_color(R.string.setting_theme_widget_row_background_color_description),
    widget_row_text_color(R.string.setting_theme_widget_row_text_color_description),
    widget_command_background_color(R.string.setting_theme_widget_command_background_color_description),
    widget_command_text_color(R.string.setting_theme_widget_command_text_color_description),
    widget_command_border_color(R.string.setting_theme_widget_command_border_color_description),
    widget_control_background_color(R.string.setting_theme_widget_control_background_color_description),
    widget_control_text_color(R.string.setting_theme_widget_control_text_color_description),
    widget_control_border_color(R.string.setting_theme_widget_control_border_color_description),

    workspace_panel_background_color(R.string.setting_theme_workspace_panel_background_color_description),
    workspace_panel_text_color(R.string.setting_theme_workspace_panel_text_color_description),
    workspace_panel_border_color(R.string.setting_theme_workspace_panel_border_color_description),
    workspace_header_background_color(R.string.setting_theme_workspace_header_background_color_description),
    workspace_header_text_color(R.string.setting_theme_workspace_header_text_color_description),
    workspace_header_border_color(R.string.setting_theme_workspace_header_border_color_description),
    workspace_output_background_color(R.string.setting_theme_workspace_output_background_color_description),
    workspace_output_text_color(R.string.setting_theme_workspace_output_text_color_description),
    workspace_input_background_color(R.string.setting_theme_workspace_input_background_color_description),
    workspace_input_text_color(R.string.setting_theme_workspace_input_text_color_description),
    workspace_control_background_color(R.string.setting_theme_workspace_control_background_color_description),
    workspace_control_text_color(R.string.setting_theme_workspace_control_text_color_description),
    workspace_control_border_color(R.string.setting_theme_workspace_control_border_color_description),

    settings_screen_color(R.string.setting_theme_settings_screen_color_description),
    settings_panel_background_color(R.string.setting_theme_settings_panel_background_color_description),
    settings_panel_text_color(R.string.setting_theme_settings_panel_text_color_description),
    settings_panel_border_color(R.string.setting_theme_settings_panel_border_color_description),
    settings_header_background_color(R.string.setting_theme_settings_header_background_color_description),
    settings_header_text_color(R.string.setting_theme_settings_header_text_color_description),
    settings_header_border_color(R.string.setting_theme_settings_header_border_color_description),
    settings_row_background_color(R.string.setting_theme_settings_row_background_color_description),
    settings_row_text_color(R.string.setting_theme_settings_row_text_color_description),
    settings_row_border_color(R.string.setting_theme_settings_row_border_color_description),
    settings_input_background_color(R.string.setting_theme_settings_input_background_color_description),
    settings_input_text_color(R.string.setting_theme_settings_input_text_color_description),
    settings_input_hint_color(R.string.setting_theme_settings_input_hint_color_description),
    settings_input_border_color(R.string.setting_theme_settings_input_border_color_description),

    dialog_scrim_color(R.string.setting_theme_dialog_scrim_color_description),
    dialog_panel_background_color(R.string.setting_theme_dialog_panel_background_color_description),
    dialog_panel_text_color(R.string.setting_theme_dialog_panel_text_color_description),
    dialog_panel_border_color(R.string.setting_theme_dialog_panel_border_color_description),
    dialog_header_background_color(R.string.setting_theme_dialog_header_background_color_description),
    dialog_header_text_color(R.string.setting_theme_dialog_header_text_color_description),
    dialog_header_border_color(R.string.setting_theme_dialog_header_border_color_description),
    overlay_scrim_color(R.string.setting_theme_overlay_scrim_color_description),
    overlay_panel_background_color(R.string.setting_theme_overlay_panel_background_color_description),
    overlay_panel_text_color(R.string.setting_theme_overlay_panel_text_color_description),
    overlay_panel_border_color(R.string.setting_theme_overlay_panel_border_color_description),
    overlay_header_background_color(R.string.setting_theme_overlay_header_background_color_description),
    overlay_header_text_color(R.string.setting_theme_overlay_header_text_color_description),
    overlay_header_border_color(R.string.setting_theme_overlay_header_border_color_description),

    ansi_black(R.string.setting_theme_ansi_black_description),
    ansi_red(R.string.setting_theme_ansi_red_description),
    ansi_green(R.string.setting_theme_ansi_green_description),
    ansi_yellow(R.string.setting_theme_ansi_yellow_description),
    ansi_blue(R.string.setting_theme_ansi_blue_description),
    ansi_magenta(R.string.setting_theme_ansi_magenta_description),
    ansi_cyan(R.string.setting_theme_ansi_cyan_description),
    ansi_white(R.string.setting_theme_ansi_white_description),
    ansi_bright_black(R.string.setting_theme_ansi_bright_black_description),
    ansi_bright_red(R.string.setting_theme_ansi_bright_red_description),
    ansi_bright_green(R.string.setting_theme_ansi_bright_green_description),
    ansi_bright_yellow(R.string.setting_theme_ansi_bright_yellow_description),
    ansi_bright_blue(R.string.setting_theme_ansi_bright_blue_description),
    ansi_bright_magenta(R.string.setting_theme_ansi_bright_magenta_description),
    ansi_bright_cyan(R.string.setting_theme_ansi_bright_cyan_description),
    ansi_bright_white(R.string.setting_theme_ansi_bright_white_description);

    private constructor(description: Int) : this(
        "auto",
        description,
        null,
        XMLPrefsSave.AUTO_COLOR,
        true
    )

    override fun parent(): XMLPrefsElement = XMLPrefsManager.XMLPrefsRoot.THEME

    override fun label(): String = name

    override fun type(): String = kind

    override fun defaultValue(): String = defaultValue

    override fun infoRes(): Int = info

    override fun invalidValues(): Array<String?>? = invalidValues

    override fun getLowercaseString(): String = label()

    override fun getString(): String = label()
}
